---


- name: "Ansible loop test"
  hosts: cisco
  vars:
    test_list:
      - "1.1.1.1"
      - "2.2.2.2"
      - "3.3.3.3"

  tasks:
    - name: "Loop"
      debug:
        msg: "Hosts: {{ item }}"
      loop: "{{ test_list }}"
