---
- name: "Playbook for test condition logic"
  hosts: all
  gather_facts: true
  connection: network_cli
  tasks:
    - name: "Task 1"
      debug:
        msg: "{{ item['key'] }} is {{ item['value']['ipv4'][0]['address']}}"
      loop: "{{ ansible_facts['net_interfaces'] | dict2items }}"
      when: item['value']['lineprotocol'] == "up"