---
- name: "IP filter test"
  hosts: all
  
  tasks:
    - name: "IP add filter config"
      vars: 
        myip:
          - "1.1.1.1"
          - "2.2.2.2"
          - "192.168.0.1"
          - "192.1680.1"
      debug:
        msg: {{ myip | ipv4 }} 