---
- name: My first playbook
  hosts: cisco
  gather_facts: false
  connection: network_cli
  become: true
  become_method: enable
  
  tasks:
    - name: OSPF config
      cisco.ios.ios_config:
        lines: 
          - router-id 33.44.88.22
        parents:
          - router ospf 19
    - name: Banner config
      cisco.ios.banner:
        banner: login
        text: >
          This 
          is 
          login
        state: present
      register: my_output
    - debug: var=my_output
    