---

-
  name: Mikrotik test playbook
  hosts: mikrotik
  tasks:
    -
      name: Gather mt facts
      community.routeros.facts:
        gather_subset: all
      register: mt_fct
    
    -
      name: print facts
      debug:
        msg: "{{ mt_fct }}"


    -
      name: remove loopback
      community.routeros.command:
        commands:
          - /ip address remove [find where interface=lo]
          - /interface bridge remove [find where name=lo]
      when: ansible_net_interfaces.lo is defined

    -
      name: print facts
      debug:
        msg: "{{ mt_fct }}"
